# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to Google Play Store - Internal Test"
  lane :internal do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'internal')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to Google Play Store - Alpha"
  lane :alpha do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'alpha')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to Google Play Store - Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play - Production"
  lane :production do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'production')
  end
end